INSERT INTO HOTEL (HOTEL_NAME, ROOM_NUMBER, ROOM_PRICE, STATUS) VALUES ('Ags', '10', 90, 0);
INSERT INTO HOTEL (HOTEL_NAME, ROOM_NUMBER, ROOM_PRICE, STATUS) VALUES ('Ags', '11', 110, 0);
INSERT INTO USER (NAME, BONUS_POINTS) VALUES ('Sai', 100);
INSERT INTO USER (NAME, BONUS_POINTS) VALUES ('Mahendra', 50);
